### ISSUE TITLE
"Just work"?

### ISSUE THREAD

**Issue by bitwombat** [carlalexander/wordpress-unit-test-demo#1]
Hi Carl - should the tests to "just work" after running composer, or am I over-expecting?

Running phpunit, I get this:

PHP Fatal error:  require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/gbell2/tmp/wordpress-unit-test-demo/tests/bootstrap.php on line 9

Is that a typo or should I have created wordpress-tests-lib?

**Comment by carlalexander** [comment]
This test suite expects you to have the WordPress test environment to run. If you haven't installed it or it's been deleted (it goes in `/tmp` by default), it's going to give you this error. You need to run `bash bin/install-wp-tests.sh wordpress_test`.

**Comment by bitwombat** [comment]
Ah, yes, beaut.  Working now, thanks.  I fork your project and add some README.md details, but I don't feel qualified.

I hadn't seen the WordPress test suite run before... 5042 tests!

**Comment by carlalexander** [comment]
Great! Glad it worked out :smile:
